version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: dbbook
    ports:
      - "5433:5432"
  web:
    build: .
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql://postgres:123456@db:5432/dbbook
    depends_on:
      - db